### PR TITLE
sync upstream main branch to downstream

### PR DESCRIPTION
**Pull request by Madhu-1**
syncing upstream main to downstream main

### CODE REVIEW

**Comment by Madhu-1** [comment]
@nixpanic upstream is not in sync with downstream?

**Comment by nixpanic** [comment]
> @nixpanic upstream is not in sync with downstream?

It is, but for some reason GitHub does not like the syncing since the `vendor/` directory was included. Maybe it got confused by the number of files, or something :man_shrugging: 

We have been cherry-picking all changes from the main branch in upstream to this repo (scripted).

**Comment by nixpanic** [comment]
https://github.com/red-hat-storage/kubernetes-csi-addons/pull/4#issue-1101619964 contains a one-line script that can do the syncing. Could you try it out to update this PR?

**Comment by Madhu-1** [comment]
> [#4 (comment)](https://github.com/red-hat-storage/kubernetes-csi-addons/pull/4#issue-1101619964) contains a one-line script that can do the syncing. Could you try it out to update this PR?

getting below errors/warnings

```
git log --format=format:"%h" --reverse origin/main...edd630a44 | xargs git cherry-pick
On branch update-main
Cherry-pick currently in progress.
  (run "git cherry-pick --continue" to continue)
  (use "git cherry-pick --skip" to skip this patch)
  (use "git cherry-pick --abort" to cancel the cherry-pick operation)

nothing to commit, working tree clean
The previous cherry-pick is now empty, possibly due to conflict resolution.
If you wish to commit it anyway, use:

    git commit --allow-empty

Otherwise, please use 'git cherry-pick --skip'
```

**Comment by Madhu-1** [comment]
> right, so at least one of the commits has already been cherry-picked now, you'll need to skip that one, or use `git cherry-pick --skip`.

having lot of merge conflicts. @nixpanic can you please take care of this one?

**Comment by nixpanic** [comment]
> > right, so at least one of the commits has already been cherry-picked now, you'll need to skip that one, or use `git cherry-pick --skip`.
> 
> having lot of merge conflicts. @nixpanic can you please take care of this one?

That is indeed weird... There should not be any conflicts, I don't know what caused this :cry:

**Comment by nixpanic** [comment]
This was resolved by force-pushing a new `main` branch to the repo. The previous state of the `main` branch is still available as [tag before/branch/reset/20220301](https://github.com/red-hat-storage/kubernetes-csi-addons/releases/tag/before%2Fbranch%2Freset%2F20220301).

**Pull request merged**
