### PR TITLE
sync downstream main with upstream main

### PR DESCRIPTION
**Pull request by Madhu-1**
regular sync downstream main with upstream main

/cherry-pick release-4.17

### CODE REVIEW

**Comment by Nikhil-Ladha** [comment]
We shouldn't be cherry-picking to release-4.17 during the dev phase.
That is handled by the sync pipeline, and is done only when we have a stable build.

**Comment by Nikhil-Ladha** [comment]
Due to this we still see a diff even after the cherry-pick, https://github.com/red-hat-storage/kubernetes-csi-addons/compare/release-4.17...red-hat-storage:kubernetes-csi-addons:main.
We might have to revert this PR if the sync fails, tomorrow after the stable build.

**Comment by Madhu-1** [comment]
> Due to this we still see a diff even after the cherry-pick, [release-4.17...red-hat-storage:kubernetes-csi-addons:main](https://github.com/red-hat-storage/kubernetes-csi-addons/compare/release-4.17...red-hat-storage:kubernetes-csi-addons:main). We might have to revert this PR if the sync fails, tomorrow after the stable build.

@Nikhil-Ladha sure i was not sure that we should not have cherry-pick PR, do we either need to manually backport or ping you to create the backport PR's for 4.17 branch?

**Comment by Nikhil-Ladha** [comment]
Until we reach dev frezze, we shouldn't be creating/doing any backports to 4.17 manually.
It will be taken care of by the sync PR whenever we have a stable build. Similar to this PR #147

**Comment by Madhu-1** [comment]
> Until we reach dev frezze, we shouldn't be creating/doing any backports to 4.17 manually. It will be taken care of by the sync PR whenever we have a stable build. Similar to this PR #147

if something is failing in CI job (like deployment/upgrade) do we need to wait until the next PR is created for 4.17 branch? until the dev freeze, we don't use release-4.17 branch and we test only the main branch?

**Comment by Nikhil-Ladha** [comment]
We use the main branch till dev freeze, so if the fix is merged in main branch that's enough.
The CI will pick up that fix/change in the next run and use that in the build.

**Comment by Madhu-1** [comment]
> We use the main branch till dev freeze, so if the fix is merged in main branch that's enough. The CI will pick up that fix/change in the next run and use that in the build.

if it fails tomorrow, we will revert back the PR, Thanks @Nikhil-Ladha

**Pull request merged**
