### PR TITLE
BUG 2309191: deploy: remove extra prefix: csi-addons-

### PR DESCRIPTION
**Pull request by Rakshith-R**
Signed-off-by: Rakshith R <rar@redhat.com>
(cherry picked from commit 3c5a75319018f6721c4efd9dd49780a1b750a42b)

### CODE REVIEW

**Comment by Madhu-1** [comment]
@Rakshith-R can you please add a commit to make the lint job success

**Comment by iPraveenParihar** [comment]
> @Rakshith-R can you please add a commit to make the lint job success

@Rakshith-R, I have included the commit that fixes the CI failure, can you rebase your PR?

**Pull request merged**
