### PR TITLE
sync upstream main branch to downstream

### PR DESCRIPTION
**Pull request by nixpanic**
Sync the upstream changes from `csi-addons/kubernetes-csi-addons:main` into the
`main` branch. The most important recent changes that we want included are:

- functional sidecar container-image
- vendored tools for building components
- ability to build a bundle container-image

This PR has been created by applying all changes from csi-addons/kubernetes-csi-addons commit edd630a44b2381a0063b7e7e6f5a9a8525d803bd (matches 49b568892dbcf64b71312a27ae64d8be89a51b04 in this repo):

```console
$ git log --format=format:"%h" --reverse origin/main...edd630a44 | xargs git cherry-pick
```

I still do not understand why GitHub was not able to create the PR correctly through the web interface.

Closes: #3

### CODE REVIEW

**Review by Rakshith-R — APPROVED** [review]

**Comment by nixpanic** [comment]
other red-hat-storage repositories seem to do manual merging of the `main` branch too... now waiting for the cherr-pick bot to do its work :crossed_fingers:

**Pull request merged**
