### PR TITLE
sync downstream with upstream

### PR DESCRIPTION
**Pull request by Madhu-1**
sync downstream main with upstream main

/assign @nixpanic 
/assign @Rakshith-R

### CODE REVIEW

**Comment by Rakshith-R** [comment]
/hold

@Madhu-1 pod url related changes are not in rook yet,

**Comment by nixpanic** [comment]
/unhold

This matches v0.5.0. Nothing should break, even if Rook does not have the enhancement (remove `--controller-ip` option from side-car) yet.

**Comment by Madhu-1** [comment]
@nixpanic @Rakshith-R this PR still need lgtm label

**Comment by Rakshith-R** [comment]
/lgtm

I think I've been testing latest image with rook old template, it works.

**Pull request merged**
