### PR TITLE
Syncing latest changes from main for kubernetes-csi-addons

### PR DESCRIPTION
**Pull request by df-build-team**
PR containing the latest commits from main branch

### CODE REVIEW

**Comment by nixpanic** [comment]
@karthik-us can you check what the problem with `getNextSchedule` could be?

**Comment by karthik-us** [comment]
@nixpanic PR: https://github.com/csi-addons/kubernetes-csi-addons/pull/530 should fix this.

**Comment by nixpanic** [comment]
> @nixpanic PR: [csi-addons#530](https://github.com/csi-addons/kubernetes-csi-addons/pull/530) should fix this.

Thanks! We'll wait for that to get merged and included in the next sync PR from the build-team.

**Comment by nixpanic** [comment]
The fix for the test is merged through #124. I don't know how this can be rebased on top of that for re-testing, but as the other PR passed CI, this one should be good too :crossed_fingers: 

/approve
/lgtm

**Comment by nixpanic** [comment]
> The fix for the test is merged through #124. I don't know how this can be rebased on top of that for re-testing, but as the other PR passed CI, this one should be good too 🤞

Oh, I see now. That PR was for the main branch, this is for backporting to release-4.16.

/hold

**Comment by karthik-us** [comment]
@Nikhil-Ladha IIRC, if there is already a PR open, the sync job won't send a new one is it? (Please correct me if I am wrong).

Since the fix for the test failure is in both u/s as well as d/s main branches, should we close this PR and wait for the next PR from the sync job to be available with the fix?

Also for 4.16 branch the base brach will still be the u/s main right, not the d/s main?

**Comment by nixpanic** [comment]
> Also for 4.16 branch the base brach will still be the u/s main right, not the d/s main?

Definitely downstream/main, as that contains downstream-only changes that we need to have in all downstream branches (like icons for the webui).

**Comment by Nikhil-Ladha** [comment]
> @Nikhil-Ladha IIRC, if there is already a PR open, the sync job won't send a new one is it? (Please correct me if I am wrong).
> 
> Since the fix for the test failure is in both u/s as well as d/s main branches, should we close this PR and wait for the next PR from the sync job to be available with the fix?

Yes, if the PR is already open a new PR won't be created.
We don't need to close this PR, once we have a new stable build that includes the latest commit from the d/s main branch, then those commits would be added to this PR itself, and we can then merge this PR.

> Also for 4.16 branch the base brach will still be the u/s main right, not the d/s main?

It is d/s main.

**Comment by karthik-us** [comment]
> > @Nikhil-Ladha IIRC, if there is already a PR open, the sync job won't send a new one is it? (Please correct me if I am wrong).
> > Since the fix for the test failure is in both u/s as well as d/s main branches, should we close this PR and wait for the next PR from the sync job to be available with the fix?
> 
> Yes, if the PR is already open a new PR won't be created. We don't need to close this PR, once we have a new stable build that includes the latest commit from the d/s main branch, then those commits would be added to this PR itself, and we can then merge this PR.
> 
> > Also for 4.16 branch the base brach will still be the u/s main right, not the d/s main?
> 
> It is d/s main.

Thanks @Nikhil-Ladha for the clarifications.

**Pull request merged**
